# Generated by Django 4.0.3 on 2022-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=20)),
                ('discription', models.CharField(max_length=255)),
                ('discountt', models.FloatField()),
            ],
        ),
    ]
